### ISSUE TITLE
Missing customizing for commercetools.cache.factory / CacheAdapterFactory

### ISSUE THREAD

**Issue by Haehnchen** [sphereio/commercetools-php-symfony#17]
The CacheAdapterFactory (`commercetools.cache.factory`) is not designed well in core component, so is has soft dependencies to several cache providers. Instead of internal try to find a suitable cache provide a way to inject a cache instance directly into constructor eg use psr-6 cache only. is will also help to support new symfony core cache component.

Also provide a configuration then to replace a given default cache service.

**Comment by jayS-de** [comment]
With [PHP-SDK 1.1](https://github.com/sphereio/commercetools-php-sdk/releases/tag/v1.1.0) I replaced the cache interface with the possibility to use a PSR-6 cache. It's also planned to use the symfony 3.1 PSR-6 cache adapters.
