### ISSUE TITLE
Case insensitive login credentials

### ISSUE THREAD

**Issue by avareldev** [sphereio/commercetools-php-symfony#71]
According to the documentation the login comparison is case insensitive:
https://docs.commercetools.com/http-api-projects-me-profile#authenticate-customer-sign-in

But in you AuthenticationProvider you are comparing the string case sensitive:
https://github.com/commercetools/commercetools-php-symfony/blob/develop/src/CustomerBundle/Security/Authentication/Provider/AuthenticationProvider.php#L93

Is this intended? I would suggest to compare lowercase strings.

**Comment by nikossvnk** [comment]
No, this was not intended. Nice catch. We'll fix it

**Comment by nikossvnk** [comment]
#72
